from __future__ import annotations

from app.infrastructure.tag_seed import DEFAULT_TAGS

SEED_ROOMS = [
    {
        "livekit_room_name": "beginner-friendly-chat",
        "topic": "Beginner Friendly Chat",
        "description": "A relaxed room for beginners to practice basic English conversation. No pressure, just friendly chatting about daily life.",
        "tags": ["beginner", "daily", "casual"],
        "agent_level": "basic",
        "english_level": "beginner",
        "max_participants": 5,
        "is_public": True,
        "status": "ACTIVE",
    },
    {
        "livekit_room_name": "business-english-pro",
        "topic": "Business English Pro",
        "description": "Practice professional vocabulary, presentations, and meeting scenarios. Perfect for working professionals.",
        "tags": ["business", "advanced", "leadership"],
        "agent_level": "advanced",
        "english_level": "advanced",
        "max_participants": 4,
        "is_public": True,
        "status": "ACTIVE",
    },
    {
        "livekit_room_name": "ielts-speaking-prep",
        "topic": "IELTS Speaking Preparation",
        "description": "Mock IELTS speaking tests with topic cards, timed responses, and peer feedback. Get exam-ready!",
        "tags": ["ielts", "exam", "education"],
        "agent_level": "full",
        "english_level": "intermediate",
        "max_participants": 3,
        "is_public": True,
        "status": "MATCHING",
    },
    {
        "livekit_room_name": "tech-talk-trends",
        "topic": "Tech Talk & Trends",
        "description": "Discuss the latest in AI, software development, and tech industry news. Great for developers and tech enthusiasts.",
        "tags": ["technology", "ai-ml", "cloud-computing"],
        "agent_level": "full",
        "english_level": "intermediate",
        "max_participants": 6,
        "is_public": True,
        "status": "ACTIVE",
    },
    {
        "livekit_room_name": "casual-weekend-vibes",
        "topic": "Casual Weekend Vibes",
        "description": "Weekend casual chat about hobbies, travel, food, and entertainment. Destress and make friends!",
        "tags": ["casual", "travel", "food", "music"],
        "agent_level": "basic",
        "english_level": "any",
        "max_participants": 8,
        "is_public": True,
        "status": "IDLE",
    },
    {
        "livekit_room_name": "academic-writing-club",
        "topic": "Academic Writing Club",
        "description": "Practice academic English: essay structure, research vocabulary, and formal presentation skills.",
        "tags": ["writing", "education", "science"],
        "agent_level": "advanced",
        "english_level": "advanced",
        "max_participants": 4,
        "is_public": True,
        "status": "MATCHING",
    },
    {
        "livekit_room_name": "creative-storytelling",
        "topic": "Creative Storytelling",
        "description": "Improve your narrative skills through creative writing and storytelling exercises. Imagination meets English practice.",
        "tags": ["writing", "film", "digital-art"],
        "agent_level": "advanced",
        "english_level": "intermediate",
        "max_participants": 5,
        "is_public": True,
        "status": "IDLE",
    },
    {
        "livekit_room_name": "pronunciation-perfection",
        "topic": "Pronunciation Perfection",
        "description": "Focus on accent reduction, intonation, and clear speech. AI-powered feedback on your pronunciation.",
        "tags": ["education", "psychology", "leadership"],
        "agent_level": "full",
        "english_level": "any",
        "max_participants": 3,
        "is_public": True,
        "status": "ACTIVE",
    },
    {
        "livekit_room_name": "interview-practice-lab",
        "topic": "Interview Practice Lab",
        "description": "Practice job interviews in English. Behavioral questions, technical interviews, and salary negotiations.",
        "tags": ["business", "leadership", "negotiation"],
        "agent_level": "full",
        "english_level": "intermediate",
        "max_participants": 2,
        "is_public": False,
        "status": "MATCHING",
    },
    {
        "livekit_room_name": "ai-and-philosophy",
        "topic": "AI & Philosophy",
        "description": "Deep discussions about artificial intelligence, consciousness, and the future of humanity — all in English.",
        "tags": ["ai-ml", "philosophy", "technology"],
        "agent_level": "full",
        "english_level": "advanced",
        "max_participants": 6,
        "is_public": True,
        "status": "ACTIVE",
    },
]

STATUS_MAP = {
    "ACTIVE": "ACTIVE",
    "MATCHING": "MATCHING",
    "IDLE": "IDLE",
    "END": "END",
}
